<h3>1</h3>

In [6]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import StandardScaler

data = [12, 18, 25, 30, 35]

df = pd.DataFrame(data)

std_scaler = StandardScaler()

scaled_data = std_scaler.fit_transform(df)

scaled_data

array([[-1.45951277],
       [-0.72975638],
       [ 0.12162606],
       [ 0.72975638],
       [ 1.3378867 ]])

<h3>2</h3>

In [21]:
person = {
    "name": ["Rohit","Raj","Rajesh","Rakesh","Rani","Nikita"],
    "gender": ["Male", np.nan, "Male", np.nan, "Female", np.nan]
}

df = pd.DataFrame(person)

df["gender"].fillna(df["gender"].mode()[0], inplace=True)

df

C:\Users\hp\AppData\Local\Temp\ipykernel_15452\480814796.py:8: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["gender"].fillna(df["gender"].mode()[0], inplace=True)

     name  gender
0   Rohit    Male
1     Raj    Male
2  Rajesh    Male
3  Rakesh    Male
4    Rani  Female
5  Nikita    Male

<h3>3</h3>

In [24]:
city = ["Delhi", "Mumbai", "Chennai", "Delhi","Mumbai"]

df = pd.DataFrame({"City": city})
encoded = pd.get_dummies(df["City"])

encoded

   Chennai  Delhi  Mumbai
0    False   True   False
1    False  False    True
2     True  False   False
3    False   True   False
4    False  False    True

<h3>4</h3>

In [20]:
data = {
    "ID":[1,2,3,4,5],
    "Age":[25, np.nan, 28, 30, np.nan],
    "Salary":[30000, 35000, np.nan, 40000, 38000]
}

df = pd.DataFrame(data)

# 1 . 
print(df.isnull())

print(df.isnull().sum())

# 2
df["Age"].fillna(df["Age"].mean(), inplace=True)

# 3
df["Salary"].fillna(df["Salary"].median(), inplace=True)

df

      ID    Age  Salary
0  False  False   False
1  False   True   False
2  False  False    True
3  False  False   False
4  False   True   False
ID        0
Age       2
Salary    1
dtype: int64

C:\Users\hp\AppData\Local\Temp\ipykernel_15452\1434225664.py:15: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["Age"].fillna(df["Age"].mean(), inplace=True)
C:\Users\hp\AppData\Local\Temp\ipykernel_15452\1434225664.py:18: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["Salary"].fillna(df["Salary"].median(), inplace=True)

   ID        Age   Salary
0   1  25.000000  30000.0
1   2  27.666667  35000.0
2   3  28.000000  36500.0
3   4  30.000000  40000.0
4   5  27.666667  38000.0