<h2>Min Max Scaling</h2>

In [1]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import MinMaxScaler, StandardScaler, RobustScaler
from scipy import stats

data = {
    'Rainfall_mm': [2, 5, 12, 20, 35, 50, 65, 40, 25, 15, 8, 3],
    'Solar_Radiation_Wm2': [120, 150, 200, 300, 450, 500, 550, 480, 350, 250, 180, 130],
    'Soil_Moisture_Level': [30, 35, 40, 55, 65, 75, 85, 70, 60, 50, 42, 33],
    'Visitors_Per_Day': [150, 200, 350, 500, 750, 900, 1000, 850, 600, 450, 300, 180],
    'Air_Quality_Index': [45, 50, 55, 60, 70, 80, 95, 85, 75, 65, 58, 48]
}

df = pd.DataFrame(data)

In [4]:
min_max_scaler = MinMaxScaler()
df['Visitors_Per_Day_MinMax'] = min_max_scaler.fit_transform(df[['Visitors_Per_Day']])
df

,Rainfall_mm,Solar_Radiation_Wm2,Soil_Moisture_Level,Visitors_Per_Day,Air_Quality_Index,Visitors_Per_Day_MinMax
0,2,120,30,150,45,0.000000
1,5,150,35,200,50,0.058824
2,12,200,40,350,55,0.235294
3,20,300,55,500,60,0.411765
4,35,450,65,750,70,0.705882
5,50,500,75,900,80,0.882353
6,65,550,85,1000,95,1.000000
7,40,480,70,850,85,0.823529
8,25,350,60,600,75,0.529412
9,15,250,50,450,65,0.352941
10,8,180,42,300,58,0.176471
11,3,130,33,180,48,0.035294

<h2>Standard Deviation</h2>

In [7]:
std_scaler = StandardScaler()
df['Visitors_Per_Day_Std'] = std_scaler.fit_transform(df[['Visitors_Per_Day']])
df.round(4)

,Rainfall_mm,Solar_Radiation_Wm2,Soil_Moisture_Level,Visitors_Per_Day,Air_Quality_Index,Visitors_Per_Day_MinMax,Visitors_Per_Day_Std
0,2,120,30,150,45,0.0000,-1.2915
1,5,150,35,200,50,0.0588,-1.1166
2,12,200,40,350,55,0.2353,-0.5918
3,20,300,55,500,60,0.4118,-0.0671
4,35,450,65,750,70,0.7059,0.8075
5,50,500,75,900,80,0.8824,1.3323
6,65,550,85,1000,95,1.0000,1.6821
7,40,480,70,850,85,0.8235,1.1574
8,25,350,60,600,75,0.5294,0.2828
9,15,250,50,450,65,0.3529,-0.2420
10,8,180,42,300,58,0.1765,-0.7667
11,3,130,33,180,48,0.0353,-1.1865

<h2>Robust Scaling</h2>

In [9]:
robust = RobustScaler()
df['robust_rain'] = robust.fit_transform(df[['Rainfall_mm']])
df.round(4)

,Rainfall_mm,Solar_Radiation_Wm2,Soil_Moisture_Level,Visitors_Per_Day,Air_Quality_Index,Visitors_Per_Day_MinMax,Visitors_Per_Day_Std,robust_rain
0,2,120,30,150,45,0.0000,-1.2915,-0.5345
1,5,150,35,200,50,0.0588,-1.1166,-0.4310
2,12,200,40,350,55,0.2353,-0.5918,-0.1897
3,20,300,55,500,60,0.4118,-0.0671,0.0862
4,35,450,65,750,70,0.7059,0.8075,0.6034
5,50,500,75,900,80,0.8824,1.3323,1.1207
6,65,550,85,1000,95,1.0000,1.6821,1.6379
7,40,480,70,850,85,0.8235,1.1574,0.7759
8,25,350,60,600,75,0.5294,0.2828,0.2586
9,15,250,50,450,65,0.3529,-0.2420,-0.0862
10,8,180,42,300,58,0.1765,-0.7667,-0.3276
11,3,130,33,180,48,0.0353,-1.1865,-0.5000